### ISSUE TITLE
To do:

### ISSUE THREAD

**Issue by decaluwe** [Cantera/workshop-materials#5]
Running to-do list.  Feel free to add comments with more items:

- [x] Finish detailed Cantera notebook
- [x] Strip solutions and delete mechanism files.
- [x] Add installation instructions from 2019 README to the 2021 README (or even better, the general repo README) and point the website to that location.
- [x] Set up and distribute link to the workshop virtual call.
- [x] Incorporate other materials (slide decks) from previous workshops as necessary.
- [x] Recruit participants for running afternoon sessions.
- [x] Set up notebooks for afternoon sessions.

**Comment by bryanwweber** [comment]
- [x] Set up gather.town space for workshops
- [x] Set up Digital Ocean JupyterHub?

**Comment by bryanwweber** [comment]
Woop! We ready!
